# Generated by Django 4.1.7 on 2023-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='image_title',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
